type CITIES_TYPE = {
  [key: string]: { city: string; postalCode: string }[];
};

const TN_CITIES = {
  Ariana: [
    { city: "Ariana", postalCode: "2080" },
    { city: "Cité Ennasr", postalCode: "2001" },
    { city: "Borj Baccouch", postalCode: "2027" },
    { city: "Soukra", postalCode: "2036" },
    { city: "Ariana Géant", postalCode: "2002" },
    { city: "Menzah 6", postalCode: "2091" },
    { city: "Cité La Gazelle", postalCode: "2083" },
  ],
  Beja: [
    { city: "Beja", postalCode: "9000" },
    { city: "Mjaz Elbab", postalCode: "9070" },
    { city: "Teboursouk", postalCode: "9040" },
    { city: "Dougga", postalCode: "9032" },
  ],
  "Ben Arous": [
    { city: "Rades Medina", postalCode: "2098" },
    { city: "Mhamdia", postalCode: "1145" },
    { city: "Hammam Lif", postalCode: "2050" },
    { city: "Radés", postalCode: "2040" },
    { city: "Ezzahra", postalCode: "2034" },
    { city: "Ben Arous", postalCode: "2013" },
    { city: "Errisala", postalCode: "2044" },
    { city: "Ezzahra El Habib", postalCode: "2065" },
    { city: "Nouvelle Médina", postalCode: "2063" },
    { city: "Mourouj 1", postalCode: "2074" },
    { city: "Mourouj 3", postalCode: "2068" },
    { city: "Megrine Riadh", postalCode: "2014" },
    { city: "Mornag", postalCode: "2090" },
    { city: "Megrine", postalCode: "2033" },
  ],
  Bizerte: [
    { city: "Bizerte", postalCode: "7000" },
    { city: "Ras Djebel", postalCode: "7070" },
    { city: "Bizerte Bab Mater", postalCode: "7061" },
    { city: "Menzel Bourguiba", postalCode: "7050" },
    { city: "MZL Bourguiba Ennajah", postalCode: "7072" },
    { city: "Mateur", postalCode: "7030" },
    { city: "Menzel Jemil", postalCode: "7080" },
  ],
  Gabes: [
    { city: "Gabès", postalCode: "6000" },
    { city: "Gabes Hached", postalCode: "6001" },
    { city: "Cité El Amel", postalCode: "6033" },
    { city: "El Hamma", postalCode: "6020" },
    { city: "Mareth", postalCode: "6080" },
  ],
  Gafsa: [
    { city: "Gafsa", postalCode: "2100" },
    { city: "Gafsa Cité Ennour", postalCode: "2123" },
    { city: "Gafsa Intilaka", postalCode: "2117" },
    { city: "Metlaoui", postalCode: "2130" },
    { city: "El Guettar", postalCode: "2180" },
    { city: "Errdayef", postalCode: "2120" },
    { city: "Gafsa Gare", postalCode: "2111" },
  ],
  Jendouba: [
    { city: "Ain Drahem", postalCode: "8130" },
    { city: "Bousalem", postalCode: "8170" },
    { city: "Tabarka", postalCode: "8110" },
    { city: "Jendouba", postalCode: "8100" },
    { city: "Ghardimaou", postalCode: "8160" },
  ],
  Kairouan: [
    { city: "Kairouan", postalCode: "3100" },
    { city: "Bouhajla", postalCode: "3180" },
    { city: "Kairouan Okba", postalCode: "3140" },
    { city: "Kairouan Sud", postalCode: "3131" },
    { city: "Oueslatia", postalCode: "3120" },
    { city: "Hajeb Laayoune", postalCode: "3160" },
    { city: "Cité Hajjem", postalCode: "3129" },
    { city: "Cherarda", postalCode: "3116" },
    { city: "Cité Ennasr Kairouan", postalCode: "3182" },
    { city: "Cité Ibn Jazzar", postalCode: "3199" },
    { city: "Haffouz", postalCode: "3130" },
  ],
  Kasserine: [
    { city: "Kasserine", postalCode: "1200" },
    { city: "Sbiba", postalCode: "1270" },
    { city: "Feryana", postalCode: "1240" },
    { city: "Tela", postalCode: "1210" },
    { city: "Sbeitla", postalCode: "1250" },
  ],
  Kebili: [
    { city: "Kebili", postalCode: "4200" },
    { city: "Douz", postalCode: "4260" },
    { city: "Kébili Biez", postalCode: "4280" },
    { city: "Souk Lahad", postalCode: "4230" },
  ],
  Kef: [
    { city: "Kef", postalCode: "7100" },
    { city: "Dahmani", postalCode: "7170" },
    { city: "Tejerouin", postalCode: "7150" },
    { city: "Kef Ouest", postalCode: "7117" },
  ],
  Mahdia: [
    { city: "Mahdia", postalCode: "5100" },
    { city: "Hekaima", postalCode: "5131" },
    { city: "Mahdia République", postalCode: "5150" },
    { city: "Chebba", postalCode: "5170" },
    { city: "Mahdia Hiboun", postalCode: "5111" },
    { city: "Ksour Essef", postalCode: "5180" },
    { city: "Souassi", postalCode: "5140" },
    { city: "El Jamm", postalCode: "5160" },
  ],
  Manouba: [
    { city: "Tebourba", postalCode: "1130" },
    { city: "Mornaguia", postalCode: "1110" },
    { city: "Denden", postalCode: "2011" },
    { city: "Manouba", postalCode: "2010" },
  ],
  Medenine: [
    { city: "Medenine", postalCode: "4100" },
    { city: "El May", postalCode: "4175" },
    { city: "Ajim", postalCode: "4135" },
    { city: "Mouensa", postalCode: "4144" },
    { city: "Midoun", postalCode: "4116" },
    { city: "Zarzis", postalCode: "4170" },
    { city: "Jerba", postalCode: "4180" },
    { city: "Jerba Aéroport", postalCode: "4120" },
    { city: "Cedouikech", postalCode: "4145" },
    { city: "Akrou", postalCode: "4176" },
    { city: "Benguerden", postalCode: "4160" },
    { city: "Souihel", postalCode: "4173" },
  ],
  Monastir: [
    { city: "Monastir", postalCode: "5000" },
    { city: "Ksar Hellal", postalCode: "5070" },
    { city: "Moknine", postalCode: "5050" },
    { city: "Jammel", postalCode: "5020" },
    { city: "Ksar Hlel Riadh", postalCode: "5016" },
    { city: "Monastir République", postalCode: "5060" },
    { city: "Teboulba", postalCode: "5080" },
  ],
  Nabeul: [
    { city: "Nabeul", postalCode: "8000" },
    { city: "Kelibia", postalCode: "8090" },
    { city: "Yasmine Hammamet", postalCode: "8057" },
    { city: "Nabeul Thameur", postalCode: "8062" },
    { city: "Béni Khiar", postalCode: "8060" },
    { city: "Korba", postalCode: "8070" },
    { city: "Mrezga", postalCode: "8058" },
    { city: "Soliman", postalCode: "8020" },
    { city: "Grombalia", postalCode: "8030" },
    { city: "Dar Chaaban Fehri", postalCode: "8011" },
    { city: "Hammamet", postalCode: "8050" },
    { city: "Menzel Temim", postalCode: "8080" },
  ],
  Sfax: [
    { city: "Sfax", postalCode: "3000" },
    { city: "Merkez Chihya", postalCode: "3041" },
    { city: "Merkez Bouacida", postalCode: "3031" },
    { city: "Cité El Habib", postalCode: "3052" },
    { city: "Sidi Abbes", postalCode: "3062" },
    { city: "Sfax Jadida", postalCode: "3027" },
    { city: "Sfax 15 Novembre", postalCode: "3089" },
    { city: "Cité Khayri", postalCode: "3079" },
    { city: "Cité Bahri", postalCode: "3064" },
    { city: "Esskhira", postalCode: "3050" },
    { city: "Karkena", postalCode: "3070" },
    { city: "Sfax Hached", postalCode: "3069" },
    { city: "El Boustène", postalCode: "3099" },
    { city: "Tyna", postalCode: "3083" },
    { city: "El Aguereb", postalCode: "3030" },
    { city: "Sakiet Ezzit", postalCode: "3021" },
    { city: "Jbeniyana", postalCode: "3080" },
    { city: "El Hencha", postalCode: "3010" },
    { city: "Sfax Maghreb Arabe", postalCode: "3049" },
    { city: "El Mahres", postalCode: "3060" },
    { city: "Sakiet Eddaier", postalCode: "3011" },
  ],
  "Sidi Bouzid": [
    { city: "Sidi Bou Zid", postalCode: "9100" },
    { city: "Benaoun", postalCode: "9120" },
    { city: "Bir El Hfay", postalCode: "9113" },
    { city: "Jilma", postalCode: "9110" },
    { city: "Meknasi", postalCode: "9140" },
    { city: "Ergueb", postalCode: "9170" },
  ],
  Siliana: [
    { city: "Siliana", postalCode: "6100" },
    { city: "Makthar", postalCode: "6140" },
    { city: "Bouarada", postalCode: "6180" },
    { city: "Rouhia", postalCode: "6150" },
  ],
  Sousse: [
    { city: "Sousse", postalCode: "4000" },
    { city: "Enfidha", postalCode: "4030" },
    { city: "Sousse Khzema", postalCode: "4051" },
    { city: "Hammam Sousse", postalCode: "4011" },
    { city: "Hammam Sousse Plage", postalCode: "4083" },
    { city: "Kalla Kebira", postalCode: "4060" },
    { city: "Sahloul", postalCode: "4054" },
    { city: "Sousse Corniche", postalCode: "4059" },
    { city: "Hammam Sousse Gharbi", postalCode: "4017" },
    { city: "Msaken", postalCode: "4070" },
    { city: "Sousse Ibn Khaldoun", postalCode: "4061" },
    { city: "Sousse Erriadh", postalCode: "4023" },
    { city: "Kantaoui", postalCode: "4089" },
  ],
  Tataouine: [
    { city: "Tataouine", postalCode: "3200" },
    { city: "Tataouine Mahrajène", postalCode: "3234" },
    { city: "Tataouine Ettahrir", postalCode: "3263" },
    { city: "Ghomrassen", postalCode: "3220" },
  ],
  Tozeur: [
    { city: "Tozeur", postalCode: "2200" },
    { city: "Nefta", postalCode: "2240" },
    { city: "Dguech", postalCode: "2260" },
    { city: "Tozeur Chokrasti", postalCode: "2210" },
  ],
  Tunis: [
    { city: "Tunis", postalCode: "1000" },
    { city: "Tunis RP", postalCode: "1000" },
    { city: "Tunis République", postalCode: "1001" },
    { city: "Monplaisir", postalCode: "1073" },
    { city: "El Manar II", postalCode: "2092" },
    { city: "Berge du Lac", postalCode: "1053" },
    { city: "Tunis Thameur", postalCode: "1069" },
    { city: "Carthage", postalCode: "2016" },
    { city: "Marsa Safsaf", postalCode: "2078" },
    { city: "Tunis Belvedère", postalCode: "1002" },
    { city: "Bardo", postalCode: "2000" },
    { city: "Tunis Hached", postalCode: "1049" },
    { city: "Cite El Mhiri", postalCode: "2045" },
    { city: "Cité Rommana", postalCode: "1068" },
    { city: "Cite Ezzouhour", postalCode: "2052" },
    { city: "Bab Menara", postalCode: "1008" },
    { city: "Bab El Khadhra", postalCode: "1075" },
    { city: "Tunis Aéroport", postalCode: "2079" },
    { city: "El Menzah", postalCode: "1004" },
    { city: "Bab Souika", postalCode: "1006" },
    { city: "Cite El Khadra", postalCode: "1003" },
  ],
  Zaghouan: [
    { city: "Zaghouan", postalCode: "1100" },
    { city: "El Fahs", postalCode: "1140" },
    { city: "Bir Mcherga", postalCode: "1141" },
    { city: "Jbel El West", postalCode: "1111" },
    { city: "Hammam Zriba", postalCode: "1152" },
    { city: "Ennadhour", postalCode: "1160" },
  ],
};

export const CITIES: CITIES_TYPE = TN_CITIES;

export function getProvinceAndPostalCode(
  cityName: string
): [string | null, string | null] {
  for (const province in CITIES) {
    const citiesList = CITIES[province];
    for (const cityObj of citiesList) {
      if (cityObj.city.toLowerCase() === cityName.toLowerCase()) {
        return [province, cityObj.postalCode];
      }
    }
  }
  return [null, null];
}
